# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

email: "nir.gilad777@gmail.com"
twitter_username: "NirGilad_"
github_username: "Nirol"
logo: "/assets/images/logo/bitcoinBig.png"

search: false

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.3"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Nir Gilad"
title_separator          : "|"
name                     : "Nir Gilad"
description              : "Software Developer & Data Scientist with experience in Bioinformatics  and CryptoCurrency" 
url                      : "https://nirol.github.io/"
repository               : "Nirol/Nirol.github.io"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache



  # mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author:
#   name             : "Nir Gilad"
#   avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
#   bio              : ""
#   location         : "Israel"
#   email            : "nir.gilad777@gmail.com"
#   links:
#     - label: "Email"
#       icon: "fas fa-fw fa-envelope-square"
#       url: mailto:nir.gilad777@gmail.com
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://nirol.github.io/"
#     - label: "Linkedin"
#       icon: "fab fa-fw fa-linkedin"
#       url: "https://www.linkedin.com/in/giladnir"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter"
#       url: "https://twitter.com/NirGilad_"

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giladnir"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:nir.gilad777@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/NirGilad_"
  
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/


defaults:
  defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
      author_profile: false

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



github: [metadata]